### ISSUE TITLE
pip failed

### ISSUE THREAD

**Issue by nagarajvernekar30** [colej/pythia#1]
I tried to install pythia on a freshly installed Ubuntu 20.04. When I run the command "conda env create -f pythia.yml",  I get error stating "Pip subprocess error:
ERROR: Package 'bleach' requires a different Python: 3.6.11 not in '>=3.7'" . To check if python version was a problem, I created virtual environment using python 3.6 but still the error appeared. The exact same error appears even when the virtual environment has python3.5.

**Comment by colej** [comment]
I think the issue is that you need python 3.7 or higher, not lower.

**Comment by nagarajvernekar30** [comment]
Yes, but in the yml file, python 3.6.11 has been mentioned as a dependency due to which only that is installed in the environment. When I try to change the version, I get package conflicts.

**Comment by Guglielmo95** [comment]
Same problem here. Is there any workaround I can try? Thanks

**Comment by colej** [comment]
I've updated the yaml such that the install works for anything with python > 3.7
